import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./providers/ClientProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Flowbite, ThemeModeScript } from "flowbite-react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Driver Benefit App",
  description: "Generated by Love in Jakarta",
  authors: {
    name: "Dimas Alamsyah",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite>
          <Provider session={session}>{children}</Provider>
        </Flowbite>
      </body>
    </html>
  );
}
